package icu.cykuta.api.config;

import org.bukkit.configuration.InvalidConfigurationException;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

/**
 * A single YAML file living in the plugin's data folder.
 * <p>
 * If the plugin bundles a resource with the same name it is used as the default:
 * the file is created from it and, on every load, missing keys (with their comments)
 * are merged in and removed keys are dropped. Files without a bundled resource are
 * simply created empty — handy for data files you fill in at runtime.
 * <p>
 * You normally obtain instances through a {@link ConfigManager}, not directly.
 */
public class ConfigFile {

    /**
     * Comment block written once above the first setting generated by a
     * plugin update, so users can tell their original file apart from
     * the generated part.
     */
    private static final List<String> GENERATED_MARKER = List.of(
            "----------------------------------",
            "        Generated Settings",
            "----------------------------------",
            "The settings below were added automatically by a plugin update,",
            "each one with its own explanation. Feel free to move them",
            "anywhere in the file.");

    private final JavaPlugin plugin;
    private final String fileName;
    private File file;
    private PluginConfiguration configuration;

    public ConfigFile(JavaPlugin plugin, String fileName) {
        this.plugin = plugin;
        this.fileName = fileName;
    }

    /**
     * Create the file if it doesn't exist and load it. Called once when the file
     * is registered.
     */
    public void register() {
        this.file = new File(plugin.getDataFolder(), fileName);

        if (!this.file.exists()) {
            createFile();
        }

        this.configuration = PluginConfiguration.loadConfiguration(this.file);

        if (hasBundledResource()) {
            matchConfig();
        }
    }

    /**
     * Create the file, copying the bundled resource if there is one, or creating
     * an empty file otherwise.
     */
    private void createFile() {
        if (hasBundledResource()) {
            plugin.saveResource(fileName, false);
            return;
        }

        try {
            File parent = this.file.getParentFile();
            if (parent != null) {
                parent.mkdirs();
            }
            this.file.createNewFile();
        } catch (IOException e) {
            throw new RuntimeException("Could not create " + fileName, e);
        }
    }

    private boolean hasBundledResource() {
        return plugin.getResource(fileName) != null;
    }

    /**
     * Sync the file with the bundled resource: new keys are copied in (together
     * with their explanation comments) and keys that no longer exist are removed.
     * The first key ever generated this way gets the {@link #GENERATED_MARKER}
     * comment above it, so everything the plugin generates ends up below it.
     */
    private void matchConfig() {
        try {
            InputStream is = plugin.getResource(fileName);
            if (is == null) {
                return;
            }

            PluginConfiguration defConfig = PluginConfiguration.loadConfiguration(is);
            String firstGeneratedKey = null;

            for (String key : defConfig.getConfigurationSection("").getKeys(true)) {
                if (!configuration.contains(key)) {
                    configuration.set(key, defConfig.get(key));
                    configuration.setComments(key, defConfig.getComments(key));
                    configuration.setInlineComments(key, defConfig.getInlineComments(key));

                    // Only root keys land at the bottom of the file,
                    // where the generated section marker belongs.
                    if (firstGeneratedKey == null && !key.contains(".")) {
                        firstGeneratedKey = key;
                    }
                }
            }

            for (String key : configuration.getConfigurationSection("").getKeys(true)) {
                if (!defConfig.contains(key)) {
                    configuration.set(key, null);
                }
            }

            if (firstGeneratedKey != null && !hasGeneratedMarker()) {
                List<String> comments = new ArrayList<>();
                comments.add(null); // Blank line separating the user part of the file
                comments.addAll(GENERATED_MARKER);
                comments.addAll(configuration.getComments(firstGeneratedKey));
                configuration.setComments(firstGeneratedKey, comments);
            }

            configuration.save(this.file);
        } catch (Exception e) {
            plugin.getLogger().severe("Could not sync " + fileName + ": " + e.getMessage());
        }
    }

    /**
     * Check if the generated section marker is already written above one of the
     * root keys of the file.
     */
    private boolean hasGeneratedMarker() {
        for (String key : configuration.getConfigurationSection("").getKeys(false)) {
            if (configuration.getComments(key).containsAll(GENERATED_MARKER)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Save the in-memory configuration back to disk.
     *
     * @throws RuntimeException if an IOException occurs.
     */
    public void save() {
        try {
            this.configuration.save(this.file);
        } catch (IOException e) {
            throw new RuntimeException("Could not save " + fileName, e);
        }
    }

    /**
     * Reload the file from disk. The file is recreated if it was deleted, and new
     * default keys are merged in. On error the previous configuration is kept.
     */
    public void reload() {
        try {
            if (!this.file.exists()) {
                createFile();
            }

            // load() clears the previous values in place, so every reference held
            // elsewhere to this PluginConfiguration sees the new values.
            this.configuration.load(this.file);

            if (hasBundledResource()) {
                matchConfig();
            }
        } catch (IOException | InvalidConfigurationException e) {
            plugin.getLogger().severe("Could not reload " + fileName + ": " + e.getMessage());
        }
    }

    /**
     * The file name (relative to the plugin data folder), e.g. {@code config.yml}.
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * The loaded configuration. The reference stays stable across reloads.
     */
    public PluginConfiguration getConfiguration() {
        return this.configuration;
    }
}
